kBit.run(KBitDir.RunForward, 50)
basic.pause(500)
kBit.run(KBitDir.RunForward, 50)
basic.pause(500)
kBit.run(KBitDir.TurnRight, 50)
basic.pause(500)
kBit.run(KBitDir.TurnLeft, 50)
basic.pause(500)
kBit.carStop()
